language: php

sudo: false

services:
  - docker
  
script:
  - docker run -V $PWD:/app phpqa/php-cs-fixer fix --dry-run

notifications:
  slack:
    rooms:
      - ipssi-d19-1:3U0tNTwfovSqXR04sBm4G5HQ#travis
